filter:
    paths: [src/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 300   # How long should we wait for code coverage (in seconds).
        runs: 1